### ISSUE TITLE
Can't compile on RedHat 6.6 (ngx_rtmp_relay_module)

### ISSUE THREAD

**Issue by silverkorn** [sergey-dryabzhinsky/nginx-rtmp-module#28]
I can't compile latest version 1.1.7.7 (https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/archive/v1.1.7.7.zip) with Nginx 1.80 (http://hg.nginx.org/nginx/archive/01d52c2b460d.tar.gz) on RHEL 6.6 x86_64 and latest from the original repos works (https://github.com/arut/nginx-rtmp-module/archive/v1.1.7.zip):
```
> make
make -f objs/Makefile
make[1]: Entering directory `/home/admin/nginx'
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -Inginx-rtmp-module-1.1.7.7  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/mail \
                -o objs/addon/nginx-rtmp-module-1.1.7.7/ngx_rtmp_relay_module.o \
                nginx-rtmp-module-1.1.7.7/ngx_rtmp_relay_module.c
cc1: warnings being treated as errors
nginx-rtmp-module-1.1.7.7/ngx_rtmp_relay_module.c: In function ‘ngx_rtmp_relay_create_connection’:
nginx-rtmp-module-1.1.7.7/ngx_rtmp_relay_module.c:504: error: value computed is not used
make[1]: *** [objs/addon/nginx-rtmp-module-1.1.7.7/ngx_rtmp_relay_module.o] Error 1
make[1]: Leaving directory `/home/admin/nginx'
make: *** [build] Error 2
```

**Comment by silverkorn** [comment]
Little blame ;)
https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/blame/master/ngx_rtmp_relay_module.c#L504

**Comment by sergey-dryabzhinsky** [comment]
Yeah, there should be used ```ngx_memcpy`` function that return ```void```.

It's default by RHEL build env to add ```-Werror``` into CFLAGS?
Try to define CFLAGS in shell: ```export CFLAGS="-O2 -pipe"``` and reconfigure nginx sources and then ```make``` it.

**Comment by silverkorn** [comment]
:+1: 

Works, thank you!

**Comment by sergey-dryabzhinsky** [comment]
It's good practice to treat warning as errors thou.
I'll try to search for such code over all module. And fix warnings.

**Comment by silverkorn** [comment]
That's really appreciated, thanks.

**Comment by sergey-dryabzhinsky** [comment]
Fixed and merged.
