### ISSUE TITLE
Can't compile on RedHat 6.6 (ngx_rtmp_notify_module)

### ISSUE THREAD

**Issue by silverkorn** [sergey-dryabzhinsky/nginx-rtmp-module#33]
I've tried with the new latest version (1.1.7.8) but here's another one like #28 :

```
> make
make -f objs/Makefile
make[1]: Entering directory `/home/admin/nginx'
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -Inginx-rtmp-module-1.1.7.8  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/mail \
                -o objs/addon/nginx-rtmp-module-1.1.7.8/ngx_rtmp_notify_module.o \
                nginx-rtmp-module-1.1.7.8/ngx_rtmp_notify_module.c
nginx-rtmp-module-1.1.7.8/ngx_rtmp_notify_module.c: In function ‘ngx_rtmp_notify_publish_handle’:
nginx-rtmp-module-1.1.7.8/ngx_rtmp_notify_module.c:1189: error: too few arguments to function ‘ngx_rtmp_send_close_method’
make[1]: *** [objs/addon/nginx-rtmp-module-1.1.7.8/ngx_rtmp_notify_module.o] Error 1
make[1]: Leaving directory `/home/admin/nginx'
make: *** [build] Error 2
```

Thanks!

**Comment by silverkorn** [comment]
*Notice, `export CFLAGS="-O2 -pipe"` has not effect this time.

**Comment by sergey-dryabzhinsky** [comment]
Damn! I was shure it fixed.

**Comment by sergey-dryabzhinsky** [comment]
Please, try again, from master branch.

**Comment by silverkorn** [comment]
It works without any `CFLAGS` set, thanks!
