### ISSUE TITLE
Build with nginx 1.12.1 on OSX

### ISSUE THREAD

**Issue by metropt** [sergey-dryabzhinsky/nginx-rtmp-module#253]
Hi,
I installed nginx and openssl using brew and now I'm trying to build rtmp module.

It failed to build with the follow error:

```
	objs/addon/nginx-rtmp-module/ngx_rtmp_bitop.o \
	objs/addon/nginx-rtmp-module/ngx_rtmp_proxy_protocol.o \
	objs/addon/hls/ngx_rtmp_hls_module.o \
	objs/addon/dash/ngx_rtmp_dash_module.o \
	objs/addon/hls/ngx_rtmp_mpegts.o \
	objs/addon/hls/ngx_rtmp_mpegts_crc.o \
	objs/addon/dash/ngx_rtmp_mp4.o \
	objs/addon/nginx-rtmp-module/ngx_rtmp_stat_module.o \
	objs/addon/nginx-rtmp-module/ngx_rtmp_control_module.o \
	objs/ngx_modules.o \
	-lpcre -lssl -lcrypto -lz
Undefined symbols for architecture x86_64:
  "_SSL_CIPHER_find", referenced from:
      _ngx_ssl_get_ciphers in ngx_event_openssl.o
  "_SSL_is_server", referenced from:
      _ngx_ssl_info_callback in ngx_event_openssl.o
      _ngx_ssl_handshake in ngx_event_openssl.o
  "_X509_check_host", referenced from:
      _ngx_ssl_check_host in ngx_event_openssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [objs/nginx] Error 1
make: *** [build] Error 2
Luiss-iMac:nginx luisalves$ 
```

I tried with dev branch.

**Comment by sergey-dryabzhinsky** [comment]
It's not rtmp-module error, it's inside nginx main code.
What openssl version was installed?
