### ISSUE TITLE
macro "__DATE__" might prevent reproducible builds on Ubuntu 16.04

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [sergey-dryabzhinsky/nginx-rtmp-module#235]
New gcc - new issues:
```
ngx_rtmp_stat_module.c:820:67: error: macro "__DATE__" might prevent reproducible builds [-Werror=date-time]
```
Should be replaced with commit hash or version tag time?

**Comment by emilorol** [comment]
Did you get around this issue?

**Comment by knightfall** [comment]
@sergey-dryabzhinsky how do I get around this issue?

**Comment by Highter87** [comment]
Just remove `-Wdate-time` from the `-with-cc-opt`
